from abc import ABC, abstractmethod
from pathlib import Path


class StorageProvider(ABC):
    @abstractmethod
    async def store(self, project_id: str, category: str, filename: str, data: bytes) -> str: ...
    @abstractmethod
    async def retrieve(self, path: str) -> bytes: ...
    @abstractmethod
    async def get_path(self, project_id: str, category: str, filename: str) -> Path: ...
    @abstractmethod
    async def exists(self, path: str) -> bool: ...
    @abstractmethod
    async def delete(self, path: str) -> None: ...
    @abstractmethod
    async def list_category(self, project_id: str, category: str) -> list[str]: ...
    @abstractmethod
    async def copy_in(self, source_file_path: str, project_id: str, category: str, filename: str) -> str: ...

