"""Add M6 feedback and revision models

Revision ID: 011ef7f71b86
Revises: c90187f2eeba
Create Date: 2026-09-15 18:49:51.296326

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '011ef7f71b86'
down_revision: Union[str, None] = 'c90187f2eeba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('timeline_events')
    op.drop_table('edit_plan_runs')
    op.drop_table('transcript_chunks')
    op.drop_table('model_result_cache')
    op.drop_table('edit_plans')
    op.drop_table('job_steps')
    op.drop_table('transcript_segments')
    op.drop_table('story_edges')
    op.drop_table('processing_jobs')
    op.drop_table('story_nodes')
    op.drop_table('narrative_elements')
    op.drop_table('projects')
    op.drop_table('edit_clips')
    op.drop_table('candidate_runs')
    op.drop_table('candidate_evidence_links')
    op.drop_table('narrative_threads')
    op.drop_table('transcript_words')
    op.drop_table('feedback_events')
    op.drop_table('candidate_segments')
    op.drop_table('story_graph_runs')
    op.drop_table('media_assets')
    op.drop_table('audio_events')
    op.drop_table('node_thread_memberships')
    op.drop_table('transcript_windows')
    op.drop_table('scenes')
    op.drop_table('transcript_runs')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transcript_runs',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('project_id', sa.VARCHAR(), nullable=True),
    sa.Column('source_asset_id', sa.VARCHAR(), nullable=True),
    sa.Column('provider', sa.VARCHAR(), nullable=True),
    sa.Column('model', sa.VARCHAR(), nullable=True),
    sa.Column('language', sa.VARCHAR(), nullable=True),
    sa.Column('configuration', sqlite.JSON(), nullable=True),
    sa.Column('derivation_signature', sa.VARCHAR(), nullable=True),
    sa.Column('status', sa.VARCHAR(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('completed_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['source_asset_id'], ['media_assets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('derivation_signature')
    )
    op.create_table('scenes',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('project_id', sa.VARCHAR(), nullable=True),
    sa.Column('source_asset_id', sa.VARCHAR(), nullable=True),
    sa.Column('start_time', sa.FLOAT(), nullable=True),
    sa.Column('end_time', sa.FLOAT(), nullable=True),
    sa.Column('duration', sa.FLOAT(), nullable=True),
    sa.Column('detector', sa.VARCHAR(), nullable=True),
    sa.Column('detector_config', sqlite.JSON(), nullable=True),
    sa.Column('confidence', sa.FLOAT(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['source_asset_id'], ['media_assets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transcript_windows',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('project_id', sa.VARCHAR(), nullable=True),
    sa.Column('source_asset_id', sa.VARCHAR(), nullable=True),
    sa.Column('transcript_run_id', sa.VARCHAR(), nullable=True),
    sa.Column('start_time', sa.FLOAT(), nullable=True),
    sa.Column('end_time', sa.FLOAT(), nullable=True),
    sa.Column('level', sa.VARCHAR(), nullable=True),
    sa.Column('parent_window_id', sa.VARCHAR(), nullable=True),
    sa.Column('summary', sa.VARCHAR(), nullable=True),
    sa.Column('key_topics', sqlite.JSON(), nullable=True),
    sa.Column('provider', sa.VARCHAR(), nullable=True),
    sa.Column('model', sa.VARCHAR(), nullable=True),
    sa.Column('prompt_version', sa.VARCHAR(), nullable=True),
    sa.Column('derivation_signature', sa.VARCHAR(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['parent_window_id'], ['transcript_windows.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['source_asset_id'], ['media_assets.id'], ),
    sa.ForeignKeyConstraint(['transcript_run_id'], ['transcript_runs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('derivation_signature')
    )
    op.create_table('node_thread_memberships',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('node_id', sa.VARCHAR(), nullable=True),
    sa.Column('thread_id', sa.VARCHAR(), nullable=True),
    sa.Column('role_in_thread', sa.VARCHAR(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['node_id'], ['story_nodes.id'], ),
    sa.ForeignKeyConstraint(['thread_id'], ['narrative_threads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audio_events',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('project_id', sa.VARCHAR(), nullable=True),
    sa.Column('source_asset_id', sa.VARCHAR(), nullable=True),
    sa.Column('start_time', sa.FLOAT(), nullable=True),
    sa.Column('end_time', sa.FLOAT(), nullable=True),
    sa.Column('event_type', sa.VARCHAR(), nullable=True),
    sa.Column('analyzer', sa.VARCHAR(), nullable=True),
    sa.Column('analyzer_config', sqlite.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['source_asset_id'], ['media_assets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('media_assets',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('project_id', sa.VARCHAR(), nullable=True),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('path', sa.VARCHAR(), nullable=True),
    sa.Column('media_type', sa.VARCHAR(), nullable=True),
    sa.Column('file_size_bytes', sa.INTEGER(), nullable=True),
    sa.Column('media_info', sqlite.JSON(), nullable=True),
    sa.Column('parent_asset_id', sa.VARCHAR(), nullable=True),
    sa.Column('derivation_signature', sa.VARCHAR(), nullable=True),
    sa.Column('producer', sa.VARCHAR(), nullable=True),
    sa.Column('producer_version', sa.VARCHAR(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['parent_asset_id'], ['media_assets.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('story_graph_runs',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('project_id', sa.VARCHAR(), nullable=True),
    sa.Column('source_asset_id', sa.VARCHAR(), nullable=True),
    sa.Column('candidate_run_id', sa.VARCHAR(), nullable=True),
    sa.Column('provider', sa.VARCHAR(), nullable=True),
    sa.Column('flash_model', sa.VARCHAR(), nullable=True),
    sa.Column('pro_model', sa.VARCHAR(), nullable=True),
    sa.Column('prompt_version', sa.VARCHAR(), nullable=True),
    sa.Column('generator_version', sa.VARCHAR(), nullable=True),
    sa.Column('configuration', sqlite.JSON(), nullable=True),
    sa.Column('derivation_signature', sa.VARCHAR(), nullable=True),
    sa.Column('status', sa.VARCHAR(), nullable=True),
    sa.Column('error_message', sa.VARCHAR(), nullable=True),
    sa.Column('node_count', sa.INTEGER(), nullable=True),
    sa.Column('edge_count', sa.INTEGER(), nullable=True),
    sa.Column('thread_count', sa.INTEGER(), nullable=True),
    sa.Column('callback_count', sa.INTEGER(), nullable=True),
    sa.Column('setup_payoff_pairs', sa.INTEGER(), nullable=True),
    sa.Column('orphan_node_count', sa.INTEGER(), nullable=True),
    sa.Column('flash_requests', sa.INTEGER(), nullable=True),
    sa.Column('pro_requests', sa.INTEGER(), nullable=True),
    sa.Column('total_input_tokens', sa.INTEGER(), nullable=True),
    sa.Column('total_output_tokens', sa.INTEGER(), nullable=True),
    sa.Column('total_latency_ms', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('completed_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['candidate_run_id'], ['candidate_runs.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['source_asset_id'], ['media_assets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('derivation_signature')
    )
    op.create_table('candidate_segments',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('run_id', sa.VARCHAR(), nullable=True),
    sa.Column('project_id', sa.VARCHAR(), nullable=True),
    sa.Column('source_asset_id', sa.VARCHAR(), nullable=True),
    sa.Column('core_start', sa.FLOAT(), nullable=True),
    sa.Column('core_end', sa.FLOAT(), nullable=True),
    sa.Column('start_time', sa.FLOAT(), nullable=True),
    sa.Column('end_time', sa.FLOAT(), nullable=True),
    sa.Column('source_signals', sqlite.JSON(), nullable=True),
    sa.Column('transcript_excerpt', sa.VARCHAR(), nullable=True),
    sa.Column('summary', sa.VARCHAR(), nullable=True),
    sa.Column('local_features', sqlite.JSON(), nullable=True),
    sa.Column('score_humor', sa.FLOAT(), nullable=True),
    sa.Column('score_reaction', sa.FLOAT(), nullable=True),
    sa.Column('score_importance', sa.FLOAT(), nullable=True),
    sa.Column('score_visual_interest', sa.FLOAT(), nullable=True),
    sa.Column('score_chat_relevance', sa.FLOAT(), nullable=True),
    sa.Column('score_novelty', sa.FLOAT(), nullable=True),
    sa.Column('score_emotional_intensity', sa.FLOAT(), nullable=True),
    sa.Column('score_story_value', sa.FLOAT(), nullable=True),
    sa.Column('score_repetition', sa.FLOAT(), nullable=True),
    sa.Column('confidence', sa.FLOAT(), nullable=True),
    sa.Column('reasoning_summary', sqlite.JSON(), nullable=True),
    sa.Column('experimental_rank', sa.FLOAT(), nullable=True),
    sa.Column('ranking_profile', sa.VARCHAR(), nullable=True),
    sa.Column('analysis_provider', sa.VARCHAR(), nullable=True),
    sa.Column('analysis_model', sa.VARCHAR(), nullable=True),
    sa.Column('prompt_version', sa.VARCHAR(), nullable=True),
    sa.Column('semantic_cache_hit', sa.VARCHAR(), nullable=True),
    sa.Column('input_tokens', sa.INTEGER(), nullable=True),
    sa.Column('output_tokens', sa.INTEGER(), nullable=True),
    sa.Column('analysis_latency_ms', sa.INTEGER(), nullable=True),
    sa.Column('escalated', sa.VARCHAR(), nullable=True),
    sa.Column('debug_label', sa.VARCHAR(), nullable=True),
    sa.Column('derivation_signature', sa.VARCHAR(), nullable=True),
    sa.Column('status', sa.VARCHAR(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_cs_project')),
    sa.ForeignKeyConstraint(['run_id'], ['candidate_runs.id'], name=op.f('fk_cs_run')),
    sa.ForeignKeyConstraint(['source_asset_id'], ['media_assets.id'], name=op.f('fk_cs_asset')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('feedback_events',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transcript_words',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('segment_id', sa.VARCHAR(), nullable=True),
    sa.Column('start_time', sa.FLOAT(), nullable=True),
    sa.Column('end_time', sa.FLOAT(), nullable=True),
    sa.Column('text', sa.VARCHAR(), nullable=True),
    sa.Column('confidence', sa.FLOAT(), nullable=True),
    sa.ForeignKeyConstraint(['segment_id'], ['transcript_segments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('narrative_threads',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('story_graph_run_id', sa.VARCHAR(), nullable=True),
    sa.Column('project_id', sa.VARCHAR(), nullable=True),
    sa.Column('title', sa.VARCHAR(), nullable=True),
    sa.Column('summary', sa.VARCHAR(), nullable=True),
    sa.Column('thread_type', sa.VARCHAR(), nullable=True),
    sa.Column('first_occurrence_time', sa.FLOAT(), nullable=True),
    sa.Column('last_occurrence_time', sa.FLOAT(), nullable=True),
    sa.Column('is_resolved', sa.INTEGER(), nullable=True),
    sa.Column('importance', sa.FLOAT(), nullable=True),
    sa.Column('confidence', sa.FLOAT(), nullable=True),
    sa.Column('provider', sa.VARCHAR(), nullable=True),
    sa.Column('model', sa.VARCHAR(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['story_graph_run_id'], ['story_graph_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('candidate_evidence_links',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('candidate_id', sa.VARCHAR(), nullable=True),
    sa.Column('evidence_type', sa.VARCHAR(), nullable=True),
    sa.Column('evidence_id', sa.VARCHAR(), nullable=True),
    sa.Column('relevance', sa.VARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidate_segments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('candidate_runs',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('project_id', sa.VARCHAR(), nullable=True),
    sa.Column('source_asset_id', sa.VARCHAR(), nullable=True),
    sa.Column('analysis_versions', sqlite.JSON(), nullable=True),
    sa.Column('provider', sa.VARCHAR(), nullable=True),
    sa.Column('model', sa.VARCHAR(), nullable=True),
    sa.Column('generator_version', sa.VARCHAR(), nullable=True),
    sa.Column('candidate_config', sqlite.JSON(), nullable=True),
    sa.Column('prompt_version', sa.VARCHAR(), nullable=True),
    sa.Column('derivation_signature', sa.VARCHAR(), nullable=True),
    sa.Column('status', sa.VARCHAR(), nullable=True),
    sa.Column('candidate_count', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('completed_at', sa.DATETIME(), nullable=True),
    sa.Column('error_message', sa.VARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['source_asset_id'], ['media_assets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('derivation_signature')
    )
    op.create_table('edit_clips',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('plan_id', sa.VARCHAR(), nullable=True),
    sa.Column('source_start', sa.FLOAT(), nullable=True),
    sa.Column('source_end', sa.FLOAT(), nullable=True),
    sa.Column('core_start', sa.FLOAT(), nullable=True),
    sa.Column('core_end', sa.FLOAT(), nullable=True),
    sa.Column('output_start', sa.FLOAT(), nullable=True),
    sa.Column('output_end', sa.FLOAT(), nullable=True),
    sa.Column('candidate_id', sa.VARCHAR(), nullable=True),
    sa.Column('narrative_thread_id', sa.VARCHAR(), nullable=True),
    sa.Column('story_node_id', sa.VARCHAR(), nullable=True),
    sa.Column('selection_reason', sa.VARCHAR(), nullable=True),
    sa.Column('priority', sa.VARCHAR(), nullable=True),
    sa.Column('confidence', sa.FLOAT(), nullable=True),
    sa.Column('locked', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidate_segments.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['edit_plans.id'], ),
    sa.ForeignKeyConstraint(['story_node_id'], ['story_nodes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('projects',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('description', sa.VARCHAR(), nullable=True),
    sa.Column('status', sa.VARCHAR(), nullable=True),
    sa.Column('source_video_path', sa.VARCHAR(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('narrative_elements',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('story_graph_run_id', sa.VARCHAR(), nullable=True),
    sa.Column('project_id', sa.VARCHAR(), nullable=True),
    sa.Column('label', sa.VARCHAR(), nullable=True),
    sa.Column('element_type', sa.VARCHAR(), nullable=True),
    sa.Column('first_seen_time', sa.FLOAT(), nullable=True),
    sa.Column('last_seen_time', sa.FLOAT(), nullable=True),
    sa.Column('description', sa.VARCHAR(), nullable=True),
    sa.Column('node_ids', sqlite.JSON(), nullable=True),
    sa.Column('confidence', sa.FLOAT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['story_graph_run_id'], ['story_graph_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('story_nodes',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('story_graph_run_id', sa.VARCHAR(), nullable=True),
    sa.Column('project_id', sa.VARCHAR(), nullable=True),
    sa.Column('node_type', sa.VARCHAR(), nullable=True),
    sa.Column('start_time', sa.FLOAT(), nullable=True),
    sa.Column('end_time', sa.FLOAT(), nullable=True),
    sa.Column('candidate_id', sa.VARCHAR(), nullable=True),
    sa.Column('title', sa.VARCHAR(), nullable=True),
    sa.Column('summary', sa.VARCHAR(), nullable=True),
    sa.Column('confidence', sa.FLOAT(), nullable=True),
    sa.Column('context_requirement', sqlite.JSON(), nullable=True),
    sa.Column('graph_narrative_value', sa.FLOAT(), nullable=True),
    sa.Column('provider', sa.VARCHAR(), nullable=True),
    sa.Column('model', sa.VARCHAR(), nullable=True),
    sa.Column('prompt_version', sa.VARCHAR(), nullable=True),
    sa.Column('chapter_index', sa.INTEGER(), nullable=True),
    sa.Column('node_metadata', sqlite.JSON(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidate_segments.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['story_graph_run_id'], ['story_graph_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('processing_jobs',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('project_id', sa.VARCHAR(), nullable=True),
    sa.Column('status', sa.VARCHAR(), nullable=True),
    sa.Column('current_stage', sa.VARCHAR(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('started_at', sa.DATETIME(), nullable=True),
    sa.Column('completed_at', sa.DATETIME(), nullable=True),
    sa.Column('error_message', sa.VARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('story_edges',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('story_graph_run_id', sa.VARCHAR(), nullable=True),
    sa.Column('source_node_id', sa.VARCHAR(), nullable=True),
    sa.Column('target_node_id', sa.VARCHAR(), nullable=True),
    sa.Column('relation_type', sa.VARCHAR(), nullable=True),
    sa.Column('confidence', sa.FLOAT(), nullable=True),
    sa.Column('dependency_strength', sa.VARCHAR(), nullable=True),
    sa.Column('dependency_strength_score', sa.FLOAT(), nullable=True),
    sa.Column('evidence_summary', sa.VARCHAR(), nullable=True),
    sa.Column('provider', sa.VARCHAR(), nullable=True),
    sa.Column('model', sa.VARCHAR(), nullable=True),
    sa.Column('prompt_version', sa.VARCHAR(), nullable=True),
    sa.Column('validated', sa.INTEGER(), nullable=True),
    sa.Column('validation_errors', sqlite.JSON(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['source_node_id'], ['story_nodes.id'], ),
    sa.ForeignKeyConstraint(['story_graph_run_id'], ['story_graph_runs.id'], ),
    sa.ForeignKeyConstraint(['target_node_id'], ['story_nodes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transcript_segments',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('transcript_run_id', sa.VARCHAR(), nullable=True),
    sa.Column('start_time', sa.FLOAT(), nullable=True),
    sa.Column('end_time', sa.FLOAT(), nullable=True),
    sa.Column('text', sa.VARCHAR(), nullable=True),
    sa.Column('speaker', sa.VARCHAR(), nullable=True),
    sa.Column('confidence', sa.FLOAT(), nullable=True),
    sa.Column('sequence', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['transcript_run_id'], ['transcript_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('job_steps',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('job_id', sa.VARCHAR(), nullable=True),
    sa.Column('stage', sa.VARCHAR(), nullable=True),
    sa.Column('status', sa.VARCHAR(), nullable=True),
    sa.Column('started_at', sa.DATETIME(), nullable=True),
    sa.Column('completed_at', sa.DATETIME(), nullable=True),
    sa.Column('input_hash', sa.VARCHAR(), nullable=True),
    sa.Column('output_hash', sa.VARCHAR(), nullable=True),
    sa.Column('algorithm_version', sa.VARCHAR(), nullable=True),
    sa.Column('error_message', sa.VARCHAR(), nullable=True),
    sa.Column('retry_count', sa.INTEGER(), nullable=True),
    sa.Column('output_paths', sqlite.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['processing_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('edit_plans',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('project_id', sa.VARCHAR(), nullable=True),
    sa.Column('run_id', sa.VARCHAR(), nullable=True),
    sa.Column('version', sa.INTEGER(), nullable=True),
    sa.Column('status', sa.VARCHAR(), nullable=True),
    sa.Column('original_duration', sa.FLOAT(), nullable=True),
    sa.Column('selected_duration', sa.FLOAT(), nullable=True),
    sa.Column('compression_ratio', sa.FLOAT(), nullable=True),
    sa.Column('clip_count', sa.INTEGER(), nullable=True),
    sa.Column('locked', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['edit_plan_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('model_result_cache',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('cache_key', sa.VARCHAR(), nullable=True),
    sa.Column('provider', sa.VARCHAR(), nullable=True),
    sa.Column('model', sa.VARCHAR(), nullable=True),
    sa.Column('prompt_version', sa.VARCHAR(), nullable=True),
    sa.Column('editorial_rules_version', sa.VARCHAR(), nullable=True),
    sa.Column('result', sqlite.JSON(), nullable=True),
    sa.Column('input_tokens', sa.INTEGER(), nullable=True),
    sa.Column('output_tokens', sa.INTEGER(), nullable=True),
    sa.Column('latency_ms', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cache_key')
    )
    op.create_table('transcript_chunks',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('run_id', sa.VARCHAR(), nullable=True),
    sa.Column('start_time', sa.FLOAT(), nullable=True),
    sa.Column('end_time', sa.FLOAT(), nullable=True),
    sa.Column('status', sa.VARCHAR(), nullable=True),
    sa.Column('result_path', sa.VARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['transcript_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('edit_plan_runs',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('project_id', sa.VARCHAR(), nullable=True),
    sa.Column('source_asset_id', sa.VARCHAR(), nullable=True),
    sa.Column('candidate_run_id', sa.VARCHAR(), nullable=True),
    sa.Column('story_graph_run_id', sa.VARCHAR(), nullable=True),
    sa.Column('target_duration_seconds', sa.FLOAT(), nullable=True),
    sa.Column('tolerance_seconds', sa.FLOAT(), nullable=True),
    sa.Column('planning_profile', sa.VARCHAR(), nullable=True),
    sa.Column('provider', sa.VARCHAR(), nullable=True),
    sa.Column('model', sa.VARCHAR(), nullable=True),
    sa.Column('prompt_version', sa.VARCHAR(), nullable=True),
    sa.Column('planner_version', sa.VARCHAR(), nullable=True),
    sa.Column('derivation_signature', sa.VARCHAR(), nullable=True),
    sa.Column('status', sa.VARCHAR(), nullable=True),
    sa.Column('error_message', sa.VARCHAR(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('completed_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['candidate_run_id'], ['candidate_runs.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['source_asset_id'], ['media_assets.id'], ),
    sa.ForeignKeyConstraint(['story_graph_run_id'], ['story_graph_runs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('derivation_signature')
    )
    op.create_table('timeline_events',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('project_id', sa.VARCHAR(), nullable=True),
    sa.Column('source_asset_id', sa.VARCHAR(), nullable=True),
    sa.Column('event_type', sa.VARCHAR(), nullable=True),
    sa.Column('start_time', sa.FLOAT(), nullable=True),
    sa.Column('end_time', sa.FLOAT(), nullable=True),
    sa.Column('producer', sa.VARCHAR(), nullable=True),
    sa.Column('producer_version', sa.VARCHAR(), nullable=True),
    sa.Column('confidence', sa.FLOAT(), nullable=True),
    sa.Column('data', sqlite.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['source_asset_id'], ['media_assets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
