"""Add provenance

Revision ID: 1ef3947bd9dd
Revises: 0001
Create Date: 2026-09-14 19:08:20.755617

"""
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = '1ef3947bd9dd'
down_revision: str | None = '0001'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
