"""add_m8_effect_models

Revision ID: 26df462e4e3e
Revises: a6bbbf9f4267
Create Date: 2026-09-15 20:02:22.807532

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26df462e4e3e'
down_revision: Union[str, None] = 'a6bbbf9f4267'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
