"""M12 Job Lease and States

Revision ID: 35a2a6996cbc
Revises: c78962687ab8
Create Date: 2026-09-18 17:40:59.005130

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35a2a6996cbc'
down_revision: Union[str, None] = 'c78962687ab8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidate_runs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('worker_id', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('started_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('heartbeat_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('lease_expires_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('attempt', sa.Integer(), nullable=True))

    with op.batch_alter_table('edit_plan_runs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('worker_id', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('started_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('heartbeat_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('lease_expires_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('attempt', sa.Integer(), nullable=True))

    with op.batch_alter_table('effect_plan_runs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('worker_id', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('started_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('heartbeat_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('lease_expires_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('attempt', sa.Integer(), nullable=True))

    with op.batch_alter_table('processing_jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('worker_id', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('heartbeat_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('lease_expires_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('attempt', sa.Integer(), nullable=True))

    with op.batch_alter_table('reference_alignment_runs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('worker_id', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('started_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('heartbeat_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('lease_expires_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('attempt', sa.Integer(), nullable=True))

    with op.batch_alter_table('render_jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('worker_id', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('heartbeat_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('lease_expires_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('attempt', sa.Integer(), nullable=True))

    with op.batch_alter_table('story_graph_runs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('worker_id', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('started_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('heartbeat_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('lease_expires_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('attempt', sa.Integer(), nullable=True))

    with op.batch_alter_table('style_application_runs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('worker_id', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('started_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('heartbeat_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('lease_expires_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('attempt', sa.Integer(), nullable=True))

    with op.batch_alter_table('transcript_runs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('worker_id', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('started_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('heartbeat_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('lease_expires_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('attempt', sa.Integer(), nullable=True))

    with op.batch_alter_table('visual_analysis_runs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('worker_id', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('started_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('heartbeat_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('lease_expires_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('attempt', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visual_analysis_runs', schema=None) as batch_op:
        batch_op.drop_column('attempt')
        batch_op.drop_column('lease_expires_at')
        batch_op.drop_column('heartbeat_at')
        batch_op.drop_column('started_at')
        batch_op.drop_column('worker_id')

    with op.batch_alter_table('transcript_runs', schema=None) as batch_op:
        batch_op.drop_column('attempt')
        batch_op.drop_column('lease_expires_at')
        batch_op.drop_column('heartbeat_at')
        batch_op.drop_column('started_at')
        batch_op.drop_column('worker_id')

    with op.batch_alter_table('style_application_runs', schema=None) as batch_op:
        batch_op.drop_column('attempt')
        batch_op.drop_column('lease_expires_at')
        batch_op.drop_column('heartbeat_at')
        batch_op.drop_column('started_at')
        batch_op.drop_column('worker_id')

    with op.batch_alter_table('story_graph_runs', schema=None) as batch_op:
        batch_op.drop_column('attempt')
        batch_op.drop_column('lease_expires_at')
        batch_op.drop_column('heartbeat_at')
        batch_op.drop_column('started_at')
        batch_op.drop_column('worker_id')

    with op.batch_alter_table('render_jobs', schema=None) as batch_op:
        batch_op.drop_column('attempt')
        batch_op.drop_column('lease_expires_at')
        batch_op.drop_column('heartbeat_at')
        batch_op.drop_column('worker_id')

    with op.batch_alter_table('reference_alignment_runs', schema=None) as batch_op:
        batch_op.drop_column('attempt')
        batch_op.drop_column('lease_expires_at')
        batch_op.drop_column('heartbeat_at')
        batch_op.drop_column('started_at')
        batch_op.drop_column('worker_id')

    with op.batch_alter_table('processing_jobs', schema=None) as batch_op:
        batch_op.drop_column('attempt')
        batch_op.drop_column('lease_expires_at')
        batch_op.drop_column('heartbeat_at')
        batch_op.drop_column('worker_id')

    with op.batch_alter_table('effect_plan_runs', schema=None) as batch_op:
        batch_op.drop_column('attempt')
        batch_op.drop_column('lease_expires_at')
        batch_op.drop_column('heartbeat_at')
        batch_op.drop_column('started_at')
        batch_op.drop_column('worker_id')

    with op.batch_alter_table('edit_plan_runs', schema=None) as batch_op:
        batch_op.drop_column('attempt')
        batch_op.drop_column('lease_expires_at')
        batch_op.drop_column('heartbeat_at')
        batch_op.drop_column('started_at')
        batch_op.drop_column('worker_id')

    with op.batch_alter_table('candidate_runs', schema=None) as batch_op:
        batch_op.drop_column('attempt')
        batch_op.drop_column('lease_expires_at')
        batch_op.drop_column('heartbeat_at')
        batch_op.drop_column('started_at')
        batch_op.drop_column('worker_id')

    # ### end Alembic commands ###
