"""Update StyleApplicationRun fields

Revision ID: 6053f702cbef
Revises: eed532d792e8
Create Date: 2026-09-17 14:58:31.448379

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6053f702cbef'
down_revision: Union[str, None] = 'eed532d792e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('style_application_runs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('style_policy_id', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('style_application_config', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('experimental', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('dry_run', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('input_candidate_run_id', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('input_story_graph_run_id', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('input_visual_analysis_run_id', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('output_edit_plan_run_id', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('output_effect_plan_run_id', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('completed_at', sa.DateTime(), nullable=True))
        batch_op.create_foreign_key('fk_style_application_runs_policy_id', 'editorial_style_policies', ['style_policy_id'], ['id'])
        batch_op.drop_column('story_graph_run_id')
        batch_op.drop_column('visual_analysis_run_id')
        batch_op.drop_column('candidate_run_id')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('style_application_runs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('candidate_run_id', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('visual_analysis_run_id', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('story_graph_run_id', sa.VARCHAR(), nullable=True))
        batch_op.drop_constraint('fk_style_application_runs_policy_id', type_='foreignkey')
        batch_op.drop_column('completed_at')
        batch_op.drop_column('output_effect_plan_run_id')
        batch_op.drop_column('output_edit_plan_run_id')
        batch_op.drop_column('input_visual_analysis_run_id')
        batch_op.drop_column('input_story_graph_run_id')
        batch_op.drop_column('input_candidate_run_id')
        batch_op.drop_column('dry_run')
        batch_op.drop_column('experimental')
        batch_op.drop_column('style_application_config')
        batch_op.drop_column('style_policy_id')

    # ### end Alembic commands ###
