"""add_m3_candidate_models

Revision ID: 93d78dd465dc
Revises: 4dc1982ff01e
Create Date: 2026-09-14 21:12:03.194723

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '93d78dd465dc'
down_revision: str | None = '4dc1982ff01e'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_result_cache',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('cache_key', sa.String(), nullable=True),
    sa.Column('provider', sa.String(), nullable=True),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('prompt_version', sa.String(), nullable=True),
    sa.Column('editorial_rules_version', sa.String(), nullable=True),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cache_key')
    )
    op.create_table('candidate_runs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=True),
    sa.Column('source_asset_id', sa.String(), nullable=True),
    sa.Column('analysis_versions', sa.JSON(), nullable=True),
    sa.Column('provider', sa.String(), nullable=True),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('generator_version', sa.String(), nullable=True),
    sa.Column('candidate_config', sa.JSON(), nullable=True),
    sa.Column('prompt_version', sa.String(), nullable=True),
    sa.Column('derivation_signature', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('candidate_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['source_asset_id'], ['media_assets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('derivation_signature')
    )
    op.create_table('transcript_windows',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=True),
    sa.Column('source_asset_id', sa.String(), nullable=True),
    sa.Column('transcript_run_id', sa.String(), nullable=True),
    sa.Column('start_time', sa.Float(), nullable=True),
    sa.Column('end_time', sa.Float(), nullable=True),
    sa.Column('level', sa.String(), nullable=True),
    sa.Column('parent_window_id', sa.String(), nullable=True),
    sa.Column('summary', sa.String(), nullable=True),
    sa.Column('key_topics', sa.JSON(), nullable=True),
    sa.Column('provider', sa.String(), nullable=True),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('prompt_version', sa.String(), nullable=True),
    sa.Column('derivation_signature', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['parent_window_id'], ['transcript_windows.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['source_asset_id'], ['media_assets.id'], ),
    sa.ForeignKeyConstraint(['transcript_run_id'], ['transcript_runs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('derivation_signature')
    )
    op.create_table('candidate_evidence_links',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('candidate_id', sa.String(), nullable=True),
    sa.Column('evidence_type', sa.String(), nullable=True),
    sa.Column('evidence_id', sa.String(), nullable=True),
    sa.Column('relevance', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidate_segments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('candidate_segments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('run_id', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('project_id', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('source_asset_id', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('core_start', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('core_end', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('start_time', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('end_time', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('source_signals', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('transcript_excerpt', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('summary', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('local_features', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('score_humor', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('score_reaction', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('score_importance', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('score_visual_interest', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('score_chat_relevance', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('score_novelty', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('score_emotional_intensity', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('score_story_value', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('score_repetition', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('confidence', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('reasoning_summary', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('experimental_rank', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('ranking_profile', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('analysis_provider', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('analysis_model', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('prompt_version', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('semantic_cache_hit', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('input_tokens', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('output_tokens', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('analysis_latency_ms', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('escalated', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('debug_label', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('derivation_signature', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.create_foreign_key('fk_cs_project', 'projects', ['project_id'], ['id'])
        batch_op.create_foreign_key('fk_cs_run', 'candidate_runs', ['run_id'], ['id'])
        batch_op.create_foreign_key('fk_cs_asset', 'media_assets', ['source_asset_id'], ['id'])
        batch_op.drop_column('scores')

    # ### end Alembic commands ###


def downgrade() -> None:
    # Simplified downgrade: recreate candidate_segments as a stub and drop new tables
    # (A full column-by-column downgrade is not practical for SQLite batch mode with named FKs)
    with op.batch_alter_table('candidate_segments', schema=None) as batch_op:
        batch_op.drop_constraint('fk_cs_asset', type_='foreignkey')
        batch_op.drop_constraint('fk_cs_run', type_='foreignkey')
        batch_op.drop_constraint('fk_cs_project', type_='foreignkey')
        batch_op.add_column(sa.Column('scores', sa.JSON(), nullable=True))
        batch_op.drop_column('created_at')
        batch_op.drop_column('status')
        batch_op.drop_column('derivation_signature')
        batch_op.drop_column('debug_label')
        batch_op.drop_column('escalated')
        batch_op.drop_column('analysis_latency_ms')
        batch_op.drop_column('output_tokens')
        batch_op.drop_column('input_tokens')
        batch_op.drop_column('semantic_cache_hit')
        batch_op.drop_column('prompt_version')
        batch_op.drop_column('analysis_model')
        batch_op.drop_column('analysis_provider')
        batch_op.drop_column('ranking_profile')
        batch_op.drop_column('experimental_rank')
        batch_op.drop_column('reasoning_summary')
        batch_op.drop_column('confidence')
        batch_op.drop_column('score_repetition')
        batch_op.drop_column('score_story_value')
        batch_op.drop_column('score_emotional_intensity')
        batch_op.drop_column('score_novelty')
        batch_op.drop_column('score_chat_relevance')
        batch_op.drop_column('score_visual_interest')
        batch_op.drop_column('score_importance')
        batch_op.drop_column('score_reaction')
        batch_op.drop_column('score_humor')
        batch_op.drop_column('local_features')
        batch_op.drop_column('summary')
        batch_op.drop_column('transcript_excerpt')
        batch_op.drop_column('source_signals')
        batch_op.drop_column('end_time')
        batch_op.drop_column('start_time')
        batch_op.drop_column('core_end')
        batch_op.drop_column('core_start')
        batch_op.drop_column('source_asset_id')
        batch_op.drop_column('project_id')
        batch_op.drop_column('run_id')

    op.drop_table('candidate_evidence_links')
    op.drop_table('transcript_windows')
    op.drop_table('candidate_runs')
    op.drop_table('model_result_cache')
