"""M10_1_manual_overrides

Revision ID: da5193c29338
Revises: 84bba7e24604
Create Date: 2026-09-16 00:38:05.596751

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da5193c29338'
down_revision: Union[str, None] = '84bba7e24604'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alignment_blocks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('replaces_id', sa.String(), nullable=True))
        batch_op.create_foreign_key('fk_alignment_blocks_replaces', 'alignment_blocks', ['replaces_id'], ['id'])

    with op.batch_alter_table('observed_effects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('replaces_id', sa.String(), nullable=True))
        batch_op.create_foreign_key('fk_observed_effects_replaces', 'observed_effects', ['replaces_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('observed_effects', schema=None) as batch_op:
        # WARNING: constraint name is None; this directive will fail as
        # rendered.  Add a name, or use a naming convention; see
        # https://alembic.sqlalchemy.org/en/latest/naming.html
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('replaces_id')
        batch_op.drop_column('is_active')

    with op.batch_alter_table('alignment_blocks', schema=None) as batch_op:
        # WARNING: constraint name is None; this directive will fail as
        # rendered.  Add a name, or use a naming convention; see
        # https://alembic.sqlalchemy.org/en/latest/naming.html
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('replaces_id')
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
