"""m11_style_policy_models

Revision ID: eed532d792e8
Revises: da5193c29338
Create Date: 2026-09-17 13:36:43.562751

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eed532d792e8'
down_revision: Union[str, None] = 'da5193c29338'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('editorial_style_policies',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('source_reference_project_id', sa.String(), nullable=True),
    sa.Column('source_style_profile_id', sa.String(), nullable=True),
    sa.Column('source_style_profile_version', sa.Integer(), nullable=True),
    sa.Column('policy_version', sa.Integer(), nullable=True),
    sa.Column('experimental', sa.Boolean(), nullable=True),
    sa.Column('signals', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['source_reference_project_id'], ['reference_projects.id'], ),
    sa.ForeignKeyConstraint(['source_style_profile_id'], ['style_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('style_policy_versions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('policy_id', sa.String(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('signals', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['policy_id'], ['editorial_style_policies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('style_application_runs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=True),
    sa.Column('style_policy_version_id', sa.String(), nullable=True),
    sa.Column('candidate_run_id', sa.String(), nullable=True),
    sa.Column('story_graph_run_id', sa.String(), nullable=True),
    sa.Column('visual_analysis_run_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('signature', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['style_policy_version_id'], ['style_policy_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('style_policy_id', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('style_policy_version', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_projects_style_policy', 'editorial_style_policies', ['style_policy_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_constraint('fk_projects_style_policy', type_='foreignkey')
        batch_op.drop_column('style_policy_version')
        batch_op.drop_column('style_policy_id')

    op.drop_table('style_application_runs')
    op.drop_table('style_policy_versions')
    op.drop_table('editorial_style_policies')
    # ### end Alembic commands ###
